fixtures:
  forge_modules:
    stdlib: 'puppetlabs-stdlib'
    apt: 'puppetlabs-apt'
    epel: 'stahnma-epel'
    wget: 'maestrodev-wget'
    archive: "puppet-archive"    
  symlinks:
    kubernetes: "#{source_dir}"
